# Generated by Django 4.0.2 on 2022-02-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[(2, 'Santanader'), (1, 'BTG Pactual')], max_length=1)),
                ('notional', models.IntegerField()),
                ('taxa_entrada', models.IntegerField()),
                ('posicao', models.CharField(choices=[(4, 'Short USD'), (1, 'Long EUR'), (3, 'Short EUR'), (2, 'Long USD')], max_length=1)),
                ('businessUnit', models.TextField(blank=True, max_length=150)),
                ('usuario', models.CharField(max_length=100)),
                ('modificacao', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
